### ISSUE TITLE
How to use NostrLMDB

### ISSUE THREAD

**Issue by reyamir** [rust-nostr/nostr-sdk-swift#2]
I'm completely new to swift development, I've successfully set up nostr-sdk-swift, and can set up client. But the problem is I cannot setup database because it control via feature flag in cargo 🥲

**Comment by yukibtc** [comment]
In the UniFFI bindings the database can be opened with:

```python
database = NostrDatabase.lmdb(path)
```

(The above code example is in python, I'm new to swift too, but is enough to adj. the syntax to make it work in swift)

In the future will be similar to the rust crates, so there will be a NostrLMDB struct.
